remove blob from Kinesis record type
this has been causing `../../node_modules/@types/aws-sdk/index.d.ts(349,33): error TS2304: Cannot find name 'Blob'`